2024-10-08T11:03:59.502999+0300 - ERROR - An error has been caught in function 'run_endpoint_function', process 'MainProcess' (7332), thread 'MainThread' (3260):
Traceback (most recent call last):

  File "C:\Users\Админ\Desktop\handler\handler.py", line 331, in <module>
    uvicorn.run(app, host='127.0.0.1', log_config="log_config.json", use_colors=True, log_level="info")
    │       │   └ <fastapi.applications.FastAPI object at 0x000001C8B8A5C9D0>
    │       └ <function run at 0x000001C8B66DAA70>
    └ <module 'uvicorn' from 'C:\\Users\\Админ\\Desktop\\handler\\venv\\lib\\site-packages\\uvicorn\\__init__.py'>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
    │      └ <function Server.run at 0x000001C8B66DA3B0>
    └ <uvicorn.server.Server object at 0x000001C8B8B4FC10>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x000001C8B66DA440>
           │       │   └ <uvicorn.server.Server object at 0x000001C8B8B4FC10>
           │       └ <function run at 0x000001C8B41EDAB0>
           └ <module 'asyncio' from 'C:\\Users\\Админ\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001C8B8B4AB90>
           │    └ <function BaseEventLoop.run_until_complete at 0x000001C8B5B73130>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001C8B5C26D40>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001C8B5B74C10>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001C8B4370670>
    └ <Handle <TaskStepMethWrapper object at 0x000001C8B8C65780>()>

  File "C:\Users\Админ\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001C8B8C65780>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001C8B8C65780>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001C8B8C65780>()>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001C8B8B9B430>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65690>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x000001C8B8A5C9D0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x000001C8B8B9B430>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65690>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65690>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001C8B8C1E590>
          └ <fastapi.applications.FastAPI object at 0x000001C8B8A5C9D0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001C8B8C40F70>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001C8B8C1E560>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x000001C8B8C1E590>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x000001C8B8C40F70>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x000001C8B8C64250>
          │                            │    └ <fastapi.routing.APIRouter object at 0x000001C8B8A236D0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x000001C8B8C1E560>
          └ <function wrap_app_handling_exceptions at 0x000001C8B87CE9E0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C40430>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x000001C8B8A236D0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C40430>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x000001C8B8A236D0>>
          └ <fastapi.routing.APIRouter object at 0x000001C8B8A236D0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\routing.py", line 774, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C40430>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x000001C8B87CFEB0>
          └ APIRoute(path='/task_panel/', name='task_panel', methods=['POST'])

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\routing.py", line 295, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C40430>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x000001C8B8BBF6D0>
          └ APIRoute(path='/task_panel/', name='task_panel', methods=['POST'])

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C40430>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x000001C8B8C65210>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x000001C8B8C404C0>
          └ <function wrap_app_handling_exceptions at 0x000001C8B87CE9E0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x000001C8B8C400D0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x000001C8B8C65...
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x000001C8B8C404C0>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x000001C8B8C65210>
                     └ <function get_request_handler.<locals>.app at 0x000001C8B8BBF640>

  File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x000001C8B87E5A20>

> File "C:\Users\Админ\Desktop\handler\venv\lib\site-packages\fastapi\routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'request': <starlette.requests.Request object at 0x000001C8B8C65210>}
                 │         └ <function task_panel at 0x000001C8B8BA6B90>
                 └ <fastapi.dependencies.models.Dependant object at 0x000001C8B8BBAAD0>

  File "C:\Users\Админ\Desktop\handler\handler.py", line 276, in task_panel
    user = await session.post(url=f"{portal_url}rest/user.current?auth={data_parsed['AUTH_ID'][0]}")
                 │       └ <function ClientSession.post at 0x000001C8B64B4DC0>
                 └ <aiohttp.client.ClientSession object at 0x000001C8B8C65390>

KeyError: 'AUTH_ID'
